[workspace]

members = [
  "compleet-core",
  "compleet-plugin",
  "compleet-sources/*"
]

exclude = [
  "compleet-client",
  "nvim-bindings",
  "old-compleet-sources",
  "treesitter-highlighter",
]

[profile.release]
lto = true
codegen-units = 1
