[workspace]

members = [
  "compleet-client",
  "compleet-common",
  "compleet-sources",
  "nvim-bindings",
]

# Sacrifice compilation speed for runtime performance.
[profile.release]
lto = "fat"
codegen-units = 1
