[package]
name = "compleet-server"
version = "0.1.0"
edition = "2021"

# Better `Mutex`es.
[dependencies.parking_lot]
version = "0.10"

# Async runtime.
[dependencies.tokio]
version = "1.17.0"
features = ["full"]
