[package]
name = "compleet-core"
version = "0.1.0"
authors = ["Riccardo Mazzarini <riccardo.mazzarini@pm.me>"]
edition = "2021"

[dependencies]
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi" }
